server:
  port: 8080
 # servlet:
   # context-path: /monitor
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

auth-server: http://sso-login:8081/uaa
spring:
  boot:
    admin:
      monitor:
        status-interval: 60000ms
      discovery:
        enabled: true
  application:
    name: admin-server
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true
security:
  oauth2:
    client:
      accessTokenUri: ${auth-server}/oauth/token
      userAuthorizationUri: ${auth-server}/oauth/authorize
      clientId: merryyou1
      clientSecret: merryyousecrect1
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key

zuul:
  sensitiveHeaders:

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web.servlet: TRACE
    org.springframework.boot.web.servlet: TRACE
    org.springframework.boot.actuate.endpoint.web.servlet: TRACE
    org.springframework.security.oauth2: TRACE
